# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.url_service:
        class: AppBundle\Service\UrlService
        arguments: ['@doctrine.orm.entity_manager']
        autowire: true
    app.shortener:
        class:   AppBundle\Utility\Shorten
        # call a static method
        factory: ['AppBundle\Utility\Shorten', create]
